const magicalPageLoader=document.createElement('script');magicalPageLoader.src='js/page-loader.js';magicalPageLoader.async=false;document.head.append(magicalPageLoader);if(!window.__wandLoader){window.__wandLoader=true;document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/wand.css">');const wandLoader=document.createElement('script');wandLoader.src='js/wand.js';document.head.append(wandLoader)}document.head.insertAdjacentHTML('beforeend','<link rel="stylesheet" href="css/book-overrides.css">');
const posters=['wuMc08IPKEatf9rnMNXvIDxqP4W','sdEOH0992YZ0QSxgXNIGLq1ToUi','aWxwnYoe8p2d2fcxOqtvAtJ72Rw','fECBtHlr0rbfwxR62iFX8In3x3J','4qCqAdHcNKeAHcK8tJ8wNJZa9cx','z7uo9zmQdQwU5ZJHFpv2Upl30i1','iGoXIpQb7Pot00EEdwpwPajheZ5','c54HpQmuwXjHq2C9wmoACjxoom3'];
const books=[
  ['Harry Potter and the Philosopher’s Stone','1997',[`Harry grows up neglected by the Dursleys, unaware that he belongs to a hidden magical world. Hagrid delivers his Hogwarts letter, introduces him to Diagon Alley, and reveals that Voldemort murdered Harry’s parents but could not kill him.`,`At Hogwarts, Harry is sorted into Gryffindor, becomes the youngest Seeker in a century, and forms a close friendship with Ron and Hermione. The three learn that the Philosopher’s Stone is hidden at school and that someone is trying to steal it.`,`Harry reaches the Stone first and confronts Professor Quirrell, who has been carrying a weakened Voldemort. Because Harry wants to protect—not use—the Stone, he receives it. His mother’s sacrifice protects him and defeats Quirrell.`],['Harry receives his Hogwarts letter.','The Sorting Hat places Harry in Gryffindor.','The trio stops Voldemort from taking the Stone.']],
  ['Harry Potter and the Chamber of Secrets','1998',[`Dobby warns Harry not to return to Hogwarts, but Harry and Ron arrive in the flying Ford Anglia after the Dursleys imprison him. Soon after, a message announces that the Chamber of Secrets has been opened.`,`Students are petrified one by one. Harry hears a voice nobody else can hear and discovers he can speak Parseltongue, making him a suspect. Hermione finds the clue: a basilisk is moving through the castle pipes.`,`In the Chamber, Harry faces the basilisk and the memory of Tom Riddle. With Fawkes’s help, he destroys Riddle’s diary with a basilisk fang, saving Ginny and unknowingly destroying Voldemort’s first Horcrux.`],['Dobby’s warning and the flying car.','The basilisk begins petrifying students.','Harry destroys Tom Riddle’s diary.']],
  ['Harry Potter and the Prisoner of Azkaban','1999',[`Sirius Black escapes Azkaban and Dementors surround Hogwarts. Harry learns the Patronus Charm from Professor Lupin, while his fear of Dementors exposes the depth of his grief for his parents.`,`The truth emerges in the Shrieking Shack: Sirius was Harry’s godfather, not the Potters’ betrayer. Peter Pettigrew framed Sirius and has been hiding for years as Ron’s pet rat, Scabbers.`,`Harry and Hermione use a Time-Turner to rescue Sirius and Buckbeak. Pettigrew escapes, allowing Voldemort’s servant to return to him, but Harry gains a father figure and masters a powerful spell.`],['Dementors board the Hogwarts Express.','The Marauder’s Map reveals hidden routes.','Sirius is proven innocent to Harry.']],
  ['Harry Potter and the Goblet of Fire','2000',[`The Triwizard Tournament comes to Hogwarts. Although underage, Harry’s name is forced from the Goblet of Fire, making him a fourth champion alongside Cedric Diggory, Fleur Delacour, and Viktor Krum.`,`Harry survives a dragon, rescues Ron from the Black Lake, and reaches the centre of a shifting maze with Cedric. The trophy is a Portkey that takes them to a graveyard.`,`Peter Pettigrew uses Harry’s blood to restore Voldemort to a body. Cedric is murdered, Harry escapes with his body, and the wizarding world begins to divide as the Ministry refuses to believe Voldemort has returned.`],['The Quidditch World Cup is attacked.','Harry faces a Hungarian Horntail.','Voldemort returns in the graveyard.']],
  ['Harry Potter and the Order of the Phoenix','2003',[`The Ministry denies Voldemort’s return and discredits Harry. Dolores Umbridge takes control at Hogwarts, banning practical Defence Against the Dark Arts and punishing students who challenge her.`,`Harry, Hermione, and Ron form Dumbledore’s Army in secret. Harry teaches fellow students defensive magic while he experiences visions connected to Voldemort’s mind.`,`Believing Sirius is in danger, Harry leads a rescue attempt to the Ministry. It is a trap; the Order arrives to fight, Sirius is killed, and Dumbledore finally reveals the prophecy linking Harry and Voldemort.`],['Dumbledore’s Army trains in the Room of Requirement.','Umbridge takes control of Hogwarts.','The battle at the Department of Mysteries.']],
  ['Harry Potter and the Half-Blood Prince','2005',[`Dumbledore shows Harry memories of Tom Riddle’s childhood and explains that Voldemort split his soul into Horcruxes. Harry must obtain a crucial memory from Horace Slughorn to learn how many fragments exist.`,`Draco Malfoy is ordered to kill Dumbledore and spends the year repairing a Vanishing Cabinet. Harry discovers a mysterious Potions book signed by the Half-Blood Prince, which improves his magic but carries darker secrets.`,`Dumbledore and Harry retrieve a false Horcrux locket from a cave. When they return, Draco lets Death Eaters into Hogwarts and Snape kills Dumbledore. Harry learns Snape was the Half-Blood Prince and chooses to hunt Horcruxes.`],['Memories reveal Voldemort’s Horcrux plan.','The cave locket is retrieved.','Dumbledore dies on the Astronomy Tower.']],
  ['Harry Potter and the Deathly Hallows — Part 1','2007',[`Harry, Ron, and Hermione leave Hogwarts to find the remaining Horcruxes as Voldemort’s Ministry hunts anyone who resists. They recover Slytherin’s locket but its influence strains their friendship.`,`The trio learns about the Deathly Hallows: the Elder Wand, Resurrection Stone, and Invisibility Cloak. Ron returns after leaving, and together they destroy the locket with the Sword of Gryffindor.`,`At Malfoy Manor, Dobby rescues the prisoners but is killed. Harry chooses to bury Dobby himself, a quiet act that clarifies what matters before the final battle.`],['The Ministry falls to Voldemort.','Ron destroys Slytherin’s locket.','Dobby rescues the trio at Malfoy Manor.']],
  ['Harry Potter and the Deathly Hallows — Part 2','2007',[`Harry, Ron, and Hermione break into Gringotts and escape on a dragon after finding Hufflepuff’s cup. They return to Hogwarts, where the school prepares for a final stand against Voldemort.`,`The Battle of Hogwarts destroys Ravenclaw’s diadem and Nagini, leaving Harry as the final accidental Horcrux. Snape’s memories reveal his devotion to Lily Potter and Dumbledore’s plan.`,`Harry willingly walks into the Forbidden Forest and survives Voldemort’s curse. In the Great Hall, the Elder Wand’s true allegiance causes Voldemort’s final spell to rebound, ending the war.`],['The Gringotts dragon escape.','The Battle of Hogwarts.','Voldemort is finally defeated.']]
];
const index=Number(document.body.dataset.book)||0, book=books[index], image=`https://image.tmdb.org/t/p/w780/${posters[index]}.jpg`;
document.title=`${book[0]} | The Wizarding Archive`;
const canonicalLink=document.querySelector('link[rel="canonical"]')||document.head.appendChild(Object.assign(document.createElement('link'),{rel:'canonical'}));const canonicalUrl=new URL('ui/book.html',document.baseURI);canonicalUrl.searchParams.set('bookId',index+1);canonicalLink.href=canonicalUrl.href;const descriptionMeta=document.querySelector('meta[name="description"]')||document.head.appendChild(Object.assign(document.createElement('meta'),{name:'description'}));descriptionMeta.content=`${book[0]} plot summary, key moments, release year, and story details from The Wizarding Archive.`;
document.querySelector('[data-fill="meta"]').textContent=`Part ${String(index+1).padStart(2,'0')} · ${book[1]}`;
document.querySelector('[data-fill="title"]').innerHTML=book[0].replace(' and ',' and <br><em>')+'</em>';
document.querySelector('[data-fill="short"]').textContent=book[0].replace('Harry Potter and ','');
document.querySelector('[data-fill="author"]').textContent='J. K. Rowling';
const cover=document.querySelector('[data-fill="cover"]');cover.src=image;cover.alt=`Movie poster for ${book[0]}`;cover.onerror=()=>{cover.src='https://image.tmdb.org/t/p/w500/4qCqAdHcNKeAHcK8tJ8wNJZa9cx.jpg'};
document.querySelector('[data-fill="scene"]').style.setProperty('--scene',`url(${image})`);
document.querySelector('[data-fill="scene-title"]').textContent=book[0].replace('Harry Potter and ','');
document.querySelector('[data-fill="summary"]').innerHTML=book[2].map(p=>`<p>${p}</p>`).join('');
document.querySelector('[data-fill="moments"]').innerHTML=book[3].map((m,i)=>`<div class="moment"><span>0${i+1}</span><p>${m}</p></div>`).join('');
const previous=document.querySelector('[data-fill="prev"]'),next=document.querySelector('[data-fill="next"]');if(index)previous.href=`book-${index}.html`;else previous.remove();if(index<7)next.href=`book-${index+2}.html`;else next.remove();
const nav=document.querySelector('.main-nav');nav.insertAdjacentHTML('beforeend','<a href="ui/characters.html">Characters</a>');const toggle=document.querySelector('.menu-toggle');const closeMenu=()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')};const closeMenuFromOutside=event=>{if(!nav.classList.contains('open'))return;const target=event.target;if(toggle.contains(target)||target.closest('.main-nav'))return;closeMenu()};toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('pointerdown',closeMenuFromOutside,true);document.addEventListener('click',closeMenuFromOutside,true);document.addEventListener('touchstart',closeMenuFromOutside,true);document.addEventListener('focusin',closeMenuFromOutside,true);window.addEventListener('scroll',closeMenu,{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add('visible')}),{threshold:.1});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
