['css/wand.css'].forEach(file => document.head.insertAdjacentHTML('beforeend', `<link rel="stylesheet" href="${file}">`));
const page = document.querySelector('.guide-page');
const guideLinks = {
  'harry-potter-horcruxes-explained.html': [['Movie order', 'ui/harry-potter-movie-order.html', 'Follow the eight films that lead to the Horcrux hunt.'], ['Ending explained', 'ui/harry-potter-ending-explained.html', 'Understand the final battle, Harry’s survival, and the Elder Wand.'], ['Daily challenge', 'ui/magic.html', 'Test your wizarding memory in the interactive archive.']],
  'harry-potter-character-guide.html': [['Characters directory', 'ui/characters.html', 'Open every profile with actor, house, and story role.'], ['Patronus list', 'ui/harry-potter-patronus-list.html', 'Explore famous Patronus animals and what they reveal.'], ['Spells explained', 'ui/harry-potter-spells-explained.html', 'Connect memorable spells to the people who cast them.']],
  'harry-potter-movie-order.html': [['Books in order', 'ui/harry-potter-books-in-order.html', 'Read the seven novels in publication order.'], ['Story timeline', 'ui/harry-potter-timeline.html', 'Place the school years and final battle in context.'], ['Horcruxes explained', 'ui/harry-potter-horcruxes-explained.html', 'Follow the hidden soul fragments across the films.']],
  'harry-potter-spells-explained.html': [['Complete spell encyclopedia', 'ui/complete-harry-potter-spell-encyclopedia.html', 'Search spells by category, effect, and story meaning.'], ['Wands explained', 'ui/harry-potter-wands-explained.html', 'Learn how cores, woods, and allegiance shape magic.'], ['House quiz', 'ui/magic.html', 'Find the Hogwarts house that matches your choices.']],
  'harry-potter-hogwarts-houses-explained.html': [['Character guide', 'ui/harry-potter-character-guide.html', 'Meet the people whose choices challenge house stereotypes.'], ['Patronus list', 'ui/harry-potter-patronus-list.html', 'Explore a different kind of magical identity.'], ['Take the quiz', 'ui/magic.html', 'Let the Sorting ceremony make its own recommendation.']],
  'harry-potter-deathly-hallows-explained.html': [['Wands explained', 'ui/harry-potter-wands-explained.html', 'Understand the Elder Wand’s allegiance.'], ['Ending explained', 'ui/harry-potter-ending-explained.html', 'See how the Hallows connect to the last battle.'], ['Movie order', 'ui/harry-potter-movie-order.html', 'Watch the story in the intended sequence.']],
  'harry-potter-spells-and-meanings.html': [['Complete spell encyclopedia', 'ui/complete-harry-potter-spell-encyclopedia.html', 'Use search and filters to browse the larger spell archive.'], ['Character guide', 'ui/harry-potter-character-guide.html', 'Meet the witches and wizards behind the magic.'], ['Play the archive', 'ui/magic.html', 'Generate a spell of your own and share the result.']],
  'harry-potter-timeline.html': [['Books in order', 'ui/harry-potter-books-in-order.html', 'Read the seven novels from first letter to final battle.'], ['Movie order', 'ui/harry-potter-movie-order.html', 'Follow all eight films in release order.'], ['Ending explained', 'ui/harry-potter-ending-explained.html', 'Understand what the final events mean.']],
  'harry-potter-books-in-order.html': [['Movie order', 'ui/harry-potter-movie-order.html', 'Compare the seven books with the eight-film adaptation.'], ['Timeline', 'ui/harry-potter-timeline.html', 'See the wizarding history around Harry’s school years.'], ['Characters', 'ui/harry-potter-character-guide.html', 'Meet the cast who carry the story forward.']],
  'harry-potter-wands-explained.html': [['Spells explained', 'ui/harry-potter-spells-and-meanings.html', 'Browse the spells that give wandwork its meaning.'], ['Deathly Hallows', 'ui/harry-potter-deathly-hallows-explained.html', 'Learn why the Elder Wand is one of three Hallows.'], ['Character guide', 'ui/harry-potter-character-guide.html', 'Connect wand allegiance to character choice.']],
  'harry-potter-patronus-list.html': [['Character guide', 'ui/harry-potter-character-guide.html', 'Explore the people behind the Patronus forms.'], ['Spell meanings', 'ui/harry-potter-spells-and-meanings.html', 'Read about Expecto Patronum and other defensive magic.'], ['Character match', 'ui/magic.html', 'Find the character whose magic matches yours.']],
  'harry-potter-ending-explained.html': [['Horcruxes explained', 'ui/harry-potter-horcruxes-explained.html', 'Review every soul fragment before the final battle.'], ['Deathly Hallows', 'ui/harry-potter-deathly-hallows-explained.html', 'Understand the three objects and their symbolism.'], ['Timeline', 'ui/harry-potter-timeline.html', 'Place the epilogue in the wider wizarding chronology.']],
  'interactive-hogwarts-map.html': [['Complete spell encyclopedia', 'ui/complete-harry-potter-spell-encyclopedia.html', 'Pair each location with the magic used there.'], ['Movie order', 'ui/harry-potter-movie-order.html', 'Follow Hogwarts across all eight films.'], ['Horcruxes explained', 'ui/harry-potter-horcruxes-explained.html', 'See why the Room of Requirement matters in the final hunt.']],
  'complete-harry-potter-spell-encyclopedia.html': [['Interactive Hogwarts map', 'interactive-hogwarts-map.html', 'Explore where the most important magic happens.'], ['Wands explained', 'ui/harry-potter-wands-explained.html', 'Connect spells to wand allegiance and wandlore.'], ['Patronus list', 'ui/harry-potter-patronus-list.html', 'Read more about Expecto Patronum and character identity.']]
};
const key = location.pathname.split('/').pop() || 'harry-potter-horcruxes-explained.html';
const related = guideLinks[key] || guideLinks['harry-potter-horcruxes-explained.html'];
if (page) {
  page.insertAdjacentHTML('beforeend', `<section class="guide-related" aria-labelledby="related-title"><p class="eyebrow"><span></span> Keep exploring</p><h2 id="related-title">A few more pages<br><em>for your next chapter.</em></h2><div class="related-grid">${related.map(([title, href, copy]) => `<a class="related-card" href="${href}"><small>Archive path</small><strong>${title}</strong><span>${copy}</span><b>Open guide ↗</b></a>`).join('')}</div></section><div class="guide-actions"><button class="guide-share" type="button" data-share="${document.title}">Share this guide ↗</button><a class="guide-back" href="index.html#guides">← Back to archive guides</a></div>`);
}
const share = document.createElement('script'); share.src = 'js/share.js'; document.head.append(share);
const wand = document.createElement('script'); wand.src = 'js/wand.js'; document.head.append(wand);
const loader = document.createElement('script'); loader.src = 'js/page-loader.js'; document.head.append(loader);
