const addPageSupport=()=>{['css/wand.css','css/magic-fixes.css'].forEach(file=>document.head.insertAdjacentHTML('beforeend',`<link rel="stylesheet" href="${file}">`));const wand=document.createElement('script');wand.src='js/wand.js';document.head.append(wand);const loader=document.createElement('script');loader.src='js/page-loader.js';document.head.append(loader)};addPageSupport();
const share=(text,button)=>window.archiveShare?window.archiveShare.share(text,button):Promise.resolve(false);
const setScore=value=>{const next=Number(localStorage.getItem('archivePoints')||0)+value;localStorage.setItem('archivePoints',next);document.querySelector('#archive-score').textContent=next};document.querySelector('#archive-score').textContent=localStorage.getItem('archivePoints')||0;
const renderChoice=(target,question,answers,onAnswer)=>{target.innerHTML=`<h3>${question}</h3><div class="answer-list">${answers.map((answer,index)=>`<button type="button" data-choice="${index}">${answer}</button>`).join('')}</div>`;target.querySelectorAll('button').forEach(button=>button.addEventListener('click',()=>onAnswer(Number(button.dataset.choice))));};
const showResult=(target,title,copy)=>{target.hidden=false;target.innerHTML=`<h3>${title}</h3><p>${copy}</p><button class="share-result" type="button">Share this result ↗</button>`;target.querySelector('button').addEventListener('click',event=>share(`${title}: ${copy}`,event.currentTarget));};
const houseTarget=document.querySelector('#house-question'),houseResult=document.querySelector('#house-result');renderChoice(houseTarget,'A first-year is lost after curfew. What do you do?',['Guide them safely back, even if it risks trouble.','Work out a clever route through the castle.','Gather friends and make sure nobody is left behind.','Find the most exciting hidden passage together.'],choice=>{const results=[['Gryffindor','Your instinct is courage: you step forward when somebody needs help.'],['Ravenclaw','Your magic is curiosity and clever problem-solving.'],['Hufflepuff','Your strength is loyalty, patience, and care for others.'],['Gryffindor','Your adventurous heart loves a brave new path.']];const result=results[choice];showResult(houseResult,result[0],result[1]);setScore(5)});
const characterTarget=document.querySelector('#character-question'),characterResult=document.querySelector('#character-result');renderChoice(characterTarget,'Your friends face an impossible problem. What is your first move?',['Research every clue before acting.','Make a plan and protect everyone.','Use humour to keep everyone brave.','Listen quietly for the detail others missed.'],choice=>{const results=[['Hermione Granger','Your mind is your sharpest spell.'],['Harry Potter','You lead with conviction and protect the people you love.'],['Ron Weasley','You bring loyalty, warmth, and bravery when it matters.'],['Luna Lovegood','You notice unusual truths and trust your own perspective.']];const result=results[choice];showResult(characterResult,result[0],result[1]);setScore(5)});
const dailyQuestions=[['Which object did Harry use to destroy Tom Riddle’s diary?',['A basilisk fang','The Elder Wand','A Time-Turner','The Marauder’s Map'],0],['Who destroyed Nagini?',['Harry Potter','Neville Longbottom','Ron Weasley','Hermione Granger'],1],['Which house was Luna Lovegood in?',['Gryffindor','Hufflepuff','Ravenclaw','Slytherin'],2],['What is Voldemort’s real name?',['Tom Marvolo Riddle','Gellert Grindelwald','Salazar Slytherin','Regulus Black'],0]];const daily=dailyQuestions[new Date().getDate()%dailyQuestions.length],dailyTarget=document.querySelector('#daily-question'),dailyResult=document.querySelector('#daily-result');renderChoice(dailyTarget,daily[0],daily[1],choice=>{const correct=choice===daily[2];showResult(dailyResult,correct?'Correct! 10 archive points':'Not quite',correct?'You know the wizarding world well. Return tomorrow for another question.':'The archive has more clues waiting for you—try the guides and come back tomorrow.');if(correct)setScore(10)});
const horcruxTarget=document.querySelector('#horcrux-question'),horcruxResult=document.querySelector('#horcrux-result');renderChoice(horcruxTarget,'Which of these was not a Horcrux?',['Helga Hufflepuff’s Cup','The Elder Wand','Rowena Ravenclaw’s Diadem','Nagini'],choice=>{const correct=choice===1;showResult(horcruxResult,correct?'You found the decoy!':'That object held a fragment of Voldemort’s soul.',correct?'The Elder Wand was a Deathly Hallow, not a Horcrux.':'Review the Horcrux archive and try again.');if(correct)setScore(10)});
const spellData={protect:['Aegis Lumina','A bright shield that turns harmful intent into harmless sparks.'],discover:['Revelare Via','Reveals hidden paths, lost notes, and overlooked clues.'],heal:['Sanare Stella','A gentle warm light that steadies a tired heart and heals small wounds.'],celebrate:['Felicis Fulgur','Fills the air with golden stars to honour a hard-won victory.']};document.querySelector('#generate-spell').addEventListener('click',()=>{const result=spellData[document.querySelector('#spell-intent').value];showResult(document.querySelector('#spell-result'),result[0],result[1]);setScore(3)});
// archive-features.js owns the rotating weekly copy so the home page and Play page stay in sync.
document.querySelector('#feedback-form').addEventListener('submit',event=>{event.preventDefault();const text=document.querySelector('#feedback-text').value.trim();const suggestions=JSON.parse(localStorage.getItem('archiveSuggestions')||'[]');suggestions.push({text,date:new Date().toISOString()});localStorage.setItem('archiveSuggestions',JSON.stringify(suggestions));document.querySelector('#feedback-status').textContent='Your suggestion has been saved. Thank you for helping the archive grow.';event.target.reset()});
const toggle=document.querySelector('.menu-toggle'),nav=document.querySelector('.main-nav'),closeMenu=()=>{nav.classList.remove('open');toggle.setAttribute('aria-expanded','false')},closeMenuFromOutside=event=>{if(!nav.classList.contains('open'))return;const target=event.target;if(toggle.contains(target)||target.closest('.main-nav'))return;closeMenu()};toggle.addEventListener('click',()=>{const open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)});document.querySelectorAll('.main-nav a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('pointerdown',closeMenuFromOutside,true);document.addEventListener('click',closeMenuFromOutside,true);document.addEventListener('touchstart',closeMenuFromOutside,true);document.addEventListener('focusin',closeMenuFromOutside,true);window.addEventListener('scroll',closeMenu,{passive:true});
