const bookPreviews=[
['2001 · Chris Columbus',"Harry Potter and the<br><em>Philosopher’s Stone</em>",'An ordinary boy discovers that he is a wizard, finds a home at Hogwarts, and faces the first attempt by Voldemort to return.',['Wonder','First year','The beginning'],'“The magic begins.”'],
['2002 · Chris Columbus','Harry Potter and the<br><em>Chamber of Secrets</em>','A hidden chamber reopens at Hogwarts, students are petrified, and Harry must confront the memory of Tom Riddle to save Ginny Weasley.',['Secrets','Basilisk','The heir'],'“The chamber has been opened.”'],
['2004 · Alfonso Cuarón','Harry Potter and the<br><em>Prisoner of Azkaban</em>','Dementors, a Time-Turner, and an escaped prisoner reveal the truth about Harry’s parents and the betrayal that changed his life.',['Patronus','Time','Marauders'],'“Happiness can be found.”'],
['2005 · Mike Newell','Harry Potter and the<br><em>Goblet of Fire</em>','Forced into the Triwizard Tournament, Harry survives impossible tasks before Voldemort returns in a graveyard.',['Tournament','Dragons','Rebirth'],'“Difficult times lie ahead.”'],
['2007 · David Yates','Harry Potter and the<br><em>Order of the Phoenix</em>','As the Ministry denies Voldemort’s return, Harry builds Dumbledore’s Army and learns of the prophecy that connects them.',['Resistance','D.A.','Prophecy'],'“Things are going to change.”'],
['2009 · David Yates','Harry Potter and the<br><em>Half-Blood Prince</em>','Dumbledore reveals the secret of Horcruxes while Harry uncovers the mystery of the Half-Blood Prince.',['Memories','Horcruxes','Sacrifice'],'“The Dark Lord is rising.”'],
['2010 · David Yates','Harry Potter and the<br><em>Deathly Hallows — Part I</em>','Harry, Ron, and Hermione leave Hogwarts to hunt Horcruxes while the wizarding world falls under Voldemort’s rule.',['The hunt','Friendship','Hallows'],'“We’re all going to keep fighting.”'],
['2011 · David Yates','Harry Potter and the<br><em>Deathly Hallows — Part II</em>','The final battle returns to Hogwarts, every Horcrux falls, and Harry faces Voldemort for the last time.',['The battle','Choice','The end'],'“It all ends here.”']
];
const previewDetail=document.querySelector('#film-detail');document.querySelectorAll('.film-tab').forEach((tab,index)=>tab.addEventListener('click',event=>{event.preventDefault();const item=bookPreviews[index];document.querySelectorAll('.film-tab').forEach(link=>link.classList.remove('active'));tab.classList.add('active');previewDetail.innerHTML=`<div class="film-number">${String(index+1).padStart(2,'0')} / 08</div><p class="film-year">${item[0]}</p><h3>${item[1]}</h3><p class="film-summary">${item[2]}</p><div class="film-tags">${item[3].map(tag=>`<span>${tag}</span>`).join('')}</div><a class="view-more" href="ui/book.html?bookId=${index+1}">View detailed story <b>→</b></a><div class="detail-footer"><span>${item[4]}</span><span class="film-dot">✦</span></div>`;previewDetail.animate([{opacity:.45,transform:'translateY(7px)'},{opacity:1,transform:'translateY(0)'}],{duration:280,easing:'ease-out'})}));document.querySelector('.film-tab.active')?.click();
